language: node_js
node_js: '9'
env:
  global:
  - REPO_SLUG=MentalNomad/btg-core-config-generator
  - secure: "lU98dcxOmA9Mk0qMWsvOn9QPj+wHsHMEFpGansmNGro5DudBswpuRAN8A2DcKqCA9hhvCk/HX6sTSETXaJ6pca7oxWA2J9e/IpQtUGjFJgcKTU2bqpSjwH+T4oLLWluYjqFCZDPSRH08RgsWEORZMueMUFmsaZo72U8YRnmUN4em50FTK2rJh5upFXyHdMcP57ZS6JSNxBgVdE1a4RqSROjiI3/i+BCuRB9XbVqpf8hYUQf2rqBP5aQTrLt5vaQCa5LHfdIrK/KI7w3EVyeD9CbwvR9AOYSjQI1Wb7Tepu/3Ua/O2L0gEFvUdOceW+3DnFGG/ONB/lU1bAR59tM8qmGISQzGFcX9wr0ZdLL3Jlzibu6g5YkPucE7mhDUfbfqteQMT4M1fQfCeIPSf/h6PijsHuNYTAfYWbP7UVr1Mp2TjNemYcIwjmS8Kg9TZO9awxru19Dtk4ltGd1PliLtrHaslkZqvdkvSq5yTisjD/XaCMfXzv39AFHjOihhZKvgyiZdQ3BRWaNAczgs1KKO6dUl/DYfUWrbzQcrUdZqKbh3oUfw69LyBHzCjizvfJniXfeq26T4hqEPV/l1yBxuSrSWoNaFEU01Wf/J1jOkVD5FbJ+WAdNZe7pmnUptLtbYMDDF6NmeC4KhWBkKKli5+TSCx8L6OejBXnbMtG/myw4="
script:
- npm run lint
- npm test
- npm run build
after_success:
- "./scripts/deploy-to-gh-pages.sh"
