language: node_js
node_js: '9'
env:
  global:
  - REPO_SLUG=MentalNomad/btg-core-config-generator
  - secure: dJEt1CxAbxsYXCG93mF64ZPCkGjvul/kaFgGcfDLoMoAD12yMnrkEoxw318N1LlaVCkbmiNJVzkW6Sf9LypqYr+Bq/mDpTgdoRvC3L7tGcIKjf0jRbfpKYsOhVJm4ZginSOkeJDRs7naJc/G6WtzxDaIp/poooWC7VM0oebtaotx/a99kasPlknJFjaCshV77RBXhlrfUKY1J/3NVTyS8aPaU3W0E3Nwf+B4IYyxQbLRyUikI/a7h/OFPFS+Yb2u2vL5rp6GG/C9fv1lrku+u5eBqhywlYZ+9xvULIvdn5wYRj1AamPQpcM09b08BxOMmefc8vP96appmLJquyLMyP8nzpjkJOpMPTYojSrIuWvfi7vGHZShtSQArHGQWhoNHbFrqJfQ576gMR2tqijvuk6VCO3uADS5ODTepM/CNaTl4oJ5EgXoV10AdmHpYcru44Jfthm/+YKDmgXtq5x2j989BULvLbsgnq1+VOwAoOhMv2zXoR0vmbh/iZ2/b0XhY0lnbcF0lZ4cTh2daRkdJXL5FL+2/RdbefShOQnCZ1qOCSESY/WgarwB3042HDViw/VlyiCw+qyK7o9CFQ4iGp24ISb80/94wlhUoqH4Kp0PAl9ivp4+MdJ6QceQZbYraUlqriSym3ypIkyrJE/1nY/WDz6wYdLCm+cgrifEUoA=
script:
- npm run lint
- npm test
- npm run build
after_success:
- "./scripts/deploy-to-gh-pages.sh"
