language: node_js
node_js: "9"

deploy:
  skip_cleanup: true

env:
  global:
    - REPO_SLUG=MentalNomad/btg-core-config-generator
    - secure: "ljz/dPa1KnZfPF1o8Yw9JjRaGHT8ZMnCFcRPdcbVjhe4gPFCX75y5Hz0W+RRBhHLvn/3aE6AwRwFIa44cZH5VYNqjEJ5MQjHcG0JCPILMSVFEdRF1SWhg/P49ZyssktpW7ceiBJdI2mVl1UAOff/hVfjyCkODe0/RI2ChsfvDqGGdeciAJZdS3Mix+T14quRB494D4nQ1S6Ig2AXhiMecJdyuCWkFYkgnosYJjezE4gA4+oFsnvfZhekrDaPtRosihSjhGlOialRbagvSI4UMnp/H/0aUMWsFu54eRj5Y1D78h87KxPaVt4+R8RqcK31ec7Nc8Re7jzP3uZMf5JMoLcs8JbOptGFd2ZztYvTWwBpscE/WNZbvkCKxUNcrehxzCx0vqqmGhnFw4rrbeu48XDZnnhsOfrPfh1ZX+auKLJZ1HW003+WQL5xg3fFixfcDr0pF2AGo40FdwWmhpjn2w4NO9bUsmGGy8tiU69mydVs28Q0X/aCh41PtHzvapN6GYxI4yI0TXH7o7n6XSx8CtKNm1U2cNz/ZQVuKNlyY7PVM9rZrEd2ykjAl/FT74lk0xQftw3Ww1Osq6vu1eDV6t7WXFHI5BPOAzmVlrG5m/edQFA1oNmqSTAfMYJ/pdQJMhJGp5J2flGOyYSSkSThnVU2nibwgkN9TdXrWBjvDDU="

script:
  - npm run lint
  - npm test
  - npm run build

after_success:
  - ./scripts/deploy-to-gh-pages.sh
